package com.cory.model.base;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import com.cory.model.BaseModel;
import lombok.Data;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Model(table = "base_data_dict", name = "数据字典", module = "base")
public class Datadict extends BaseModel {

    @Field(name = "type", type = CoryDbType.BIGINT, label = "类型")
    private Integer type;

    @Field(name = "value", type = CoryDbType.VARCHAR, label = "值")
    private String value;

    @Field(name = "sn", type = CoryDbType.INT, label = "排序顺序")
    private Integer sn;

    @Field(name = "description", type = CoryDbType.VARCHAR, label = "描述")
    private String description;

    @Field(name = "type", type = CoryDbType.BIGINT, label = "是否显示")
    private Boolean showable;

    //display only
    private String typeDescription;
    private String showableName;

}
