package com.cory.model.base;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import com.cory.model.BaseModel;
import lombok.Data;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Model(table = "base_feedback", name = "反馈", module = "base")
public class Feedback extends BaseModel {

    @Field(name = "content", type = CoryDbType.VARCHAR, label = "内容")
    private String content;
    
}
