package com.cory.model.base;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import com.cory.model.BaseModel;
import lombok.Data;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Model(table = "base_resource", name = "资源", module = "base")
public class Resource extends BaseModel {

    @Field(name = "value", type = CoryDbType.VARCHAR, label = "值")
    private String value;

    @Field(name = "type", type = CoryDbType.VARCHAR, label = "类型")
    private String type;

    @Field(name = "description", type = CoryDbType.VARCHAR, label = "说明")
    private String description;
    
}
