package com.cory.model.base;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import com.cory.model.BaseModel;
import lombok.Data;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Model(name = "资源", module = "base")
public class Resource extends BaseModel {

    @Field(label = "值", type = CoryDbType.VARCHAR, len = 200)
    private String value;

    @Field(label = "类型", type = CoryDbType.VARCHAR, len = 50)
    private String type;

    @Field(label = "说明", type = CoryDbType.VARCHAR, len = 200)
    private String description;
    
}
