package com.cory.model.base;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import com.cory.model.BaseModel;
import lombok.Data;

import java.util.List;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Model(table = "base_role", name = "角色", module = "base")
public class Role extends BaseModel {

    @Field(name = "name", type = CoryDbType.VARCHAR, label = "名称")
    private String name;

    @Field(name = "description", type = CoryDbType.VARCHAR, label = "说明")
    private String description;

    private List<Resource> resources;
    
}
