package com.cory.model.base;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import com.cory.enums.base.UserStatus;
import com.cory.enums.base.UserType;
import com.cory.model.BaseModel;
import lombok.Data;

import java.util.List;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Model(table = "base_user", name = "用户", module = "base")
public class User extends BaseModel {

    @Field(name = "phone", type = CoryDbType.VARCHAR, label = "电话")
    private String phone;

    @Field(name = "email", type = CoryDbType.VARCHAR, label = "邮箱")
    private String email;

    @Field(name = "password", type = CoryDbType.VARCHAR, label = "密码", showable = false)
    private String password;

    @Field(name = "thirdparty_id", type = CoryDbType.VARCHAR, label = "第三方账号ID")
    private String thirdpartyId;

    @Field(name = "thirdparty_type", type = CoryDbType.VARCHAR, label = "第三方账号类型")
    private String thirdpartyType;

    @Field(name = "type", type = CoryDbType.VARCHAR, label = "类型")
    private String type;

    @Field(name = "status", type = CoryDbType.VARCHAR, label = "状态")
    private String status;

    @Field(name = "level", type = CoryDbType.VARCHAR, label = "级别")
    private String level;

    @Field(name = "extra_info", type = CoryDbType.VARCHAR, label = "额外信息", showable = false)
    private String extraInfo;

    private List<Role> roles;

    public String getLogonId() {
        if (UserType.QQ.name().equals(this.getType())
                || UserType.WEIBO.name().equals(this.getType())
                || UserType.WEIXIN.name().equals(this.getType())) {
            return thirdpartyId;
        }
        return phone;
    }

    public boolean isDisabled() {
        if (UserStatus.NORMAL.name().equals(this.getStatus())) {
            return false;
        } else {
            return true;
        }
    }
}
