package com.cory.sevice.base;

import com.cory.dao.base.FeedbackDao;
import com.cory.model.base.Feedback;
import com.cory.service.BaseService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Service
@Transactional
public class FeedbackService extends BaseService<Feedback> {

    @Autowired
    private FeedbackDao feedbackDao;

    public FeedbackDao getDao() {
        return feedbackDao;
    }
}
