package com.cory.sevice.base;

import com.cory.constant.base.CacheConstants;
import com.cory.dao.base.RoleResourceRelDao;
import com.cory.model.base.RoleResourceRel;
import com.cory.service.BaseService;
import org.apache.commons.collections4.CollectionUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Service
@Transactional
public class RoleResourceRelService extends BaseService<RoleResourceRel> {

    @Autowired
    private RoleResourceRelDao roleResourceRelDao;

    public RoleResourceRelDao getDao() {
        return roleResourceRelDao;
    }

    @CacheEvict(value = {CacheConstants.User, CacheConstants.Role, CacheConstants.Resource}, allEntries = true)
    public void assign(List<RoleResourceRel> roleResourceRelList) {
        if (CollectionUtils.isEmpty(roleResourceRelList)) {
            return;
        }
        roleResourceRelDao.deleteByRole(roleResourceRelList.get(0).getRoleId());
        for (RoleResourceRel roleResourceRel : roleResourceRelList) {
            roleResourceRelDao.add(roleResourceRel);
        }
    }
}
