package com.cory.model;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Model(name = "访问统计", module = "base", createable = false, updateable = false, deleteable = false)
public class AccessCount extends BaseModel {

    @Field(label = "日", type = CoryDbType.VARCHAR, filtered = true, len = 20)
    private String day;

    @Field(label = "小时", type = CoryDbType.VARCHAR, filtered = true, len = 20)
    private String hour;

    @Field(label = "URI", type = CoryDbType.VARCHAR, filtered = true)
    private String uri;

    @Field(label = "访问次数", type = CoryDbType.INT)
    private Integer accessCount;

}
