package com.cory.model;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import com.cory.db.enums.FilterType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Model(name = "操作日志", module = "base", createable = false, updateable = false, deleteable = false)
public class ActionLog extends BaseModel {

    @NotEmpty
    @Field(label = "关联对象类型", type = CoryDbType.VARCHAR, filtered = true)
    private String objectType;

    @NotNull
    @Field(label = "关联对象ID", type = CoryDbType.VARCHAR, filtered = true)
    private String objectId;

    @NotNull
    @Field(label = "日志内容", type = CoryDbType.TEXT)
    private String log;

    @NotEmpty
    @Field(label = "操作人", type = CoryDbType.VARCHAR)
    private String operator;

    @NotNull
    @Field(label = "操作时间", type = CoryDbType.DATETIME)
    private Date operateTime;

}
