package com.cory.model;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

/**
 * 10秒一次，执行完后自动删除。每次添加时添加到所有机器，执行后删除
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Model(name = "集群任务", module = "base", createable = false, updateable = false, deleteable = false, logicDelete = true)
public class ClusterJob extends BaseModel {

    private static final long serialVersionUID = 5986818325581884185L;

    @NotNull
    @Field(label = "任务编码", type = CoryDbType.VARCHAR, filtered = true)
    private String code;

    @NotNull
    @Field(label = "任务名称", type = CoryDbType.VARCHAR)
    private String name;

    @NotEmpty
    @Field(label = "执行任务IP&端口", type = CoryDbType.VARCHAR, filtered = true, desc = "IP&端口：192.168.0.1:8080")
    private String ip;

    @Field(label = "参数", type = CoryDbType.TEXT, desc = "不同的任务自行定义", nullable = true)
    private String param;

}
