package com.cory.model;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import com.cory.enums.ExportJobStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Model(name = "导出任务", module = "base", createable = false, updateable = false, deleteable = false)
public class ExportJob extends BaseModel {

    private static final long serialVersionUID = 5986818325581884185L;

    /**
     * 用户自定义，用于隔离不同的导出数据。在获取导出列表时用到。要唯一，这样在显示导出列表的时候才能正确显示，如果A和B都用了同一个type，那么在A或者B显示时，都会显示两个模块的导出数据
     */
    @NotNull
    @Field(label = "任务类型", type = CoryDbType.VARCHAR, filtered = true)
    private String type;

    @NotNull
    @Field(label = "任务编码", type = CoryDbType.VARCHAR, filtered = true)
    private String code;

    @Field(label = "状态", type = CoryDbType.ENUM, filtered = true)
    private ExportJobStatus status;

    @NotEmpty
    @Field(label = "执行任务IP&端口", type = CoryDbType.VARCHAR, desc = "IP&端口：192.168.0.1:8080")
    private String ip;

    @Field(label = "下载地址", type = CoryDbType.VARCHAR, nullable = true, desc = "运行成功后才有")
    private String downloadUrl;

    @Field(label = "错误信息", type = CoryDbType.VARCHAR, nullable = true, desc = "运行失败时有")
    private String errorMsg;

}
