package com.cory.model;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import com.cory.enums.ResourceType;
import lombok.Data;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Model(name = "资源", module = "base", deleteable = false, createable = false, updateable = false)
public class Resource extends BaseModel {

    @NotEmpty
    @Field(label = "值", type = CoryDbType.VARCHAR, len = 200)
    private String value;

    @NotNull
    @Field(label = "类型", type = CoryDbType.ENUM, len = 50)
    private ResourceType type;

    @NotEmpty
    @Field(label = "说明", type = CoryDbType.VARCHAR, len = 200)
    private String description;
    
}
