package com.cory.model;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import lombok.Data;

import javax.validation.constraints.NotEmpty;
import java.util.List;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Model(name = "角色", module = "base")
public class Role extends BaseModel {

    @NotEmpty
    @Field(label = "名称", type = CoryDbType.VARCHAR, len = 100)
    private String name;

    @NotEmpty
    @Field(label = "说明", type = CoryDbType.VARCHAR, len = 200)
    private String description;

    private List<Resource> resources;
    
}
