package com.cory.model;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import com.cory.model.BaseModel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Model(name = "角色资源关系", module = "base")
public class RoleResourceRel extends BaseModel {

    private static final long serialVersionUID = -9193201518045089665L;

    @Field(label = "角色ID", type = CoryDbType.BIGINT)
    private Integer roleId;

    @Field(label = "资源ID", type = CoryDbType.BIGINT)
    private Integer resourceId;

}
