package com.cory.model;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotEmpty;
import java.util.List;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Model(name = "角色", module = "base")
public class Role extends BaseModel {

    private static final long serialVersionUID = -4469732554019114003L;

    @NotEmpty
    @Field(label = "名称", type = CoryDbType.VARCHAR, len = 100, filtered = true)
    private String name;

    @NotEmpty
    @Field(label = "说明", type = CoryDbType.VARCHAR, len = 200)
    private String description;

    private List<Resource> resources;
    
}
