package com.cory.model;

import com.cory.db.annotations.Model;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Model(name = "SQL", module = "sql", noTable = true)
public class SqlModel extends BaseModel {}
