package com.cory.model;

import com.cory.db.annotations.Model;
import lombok.Data;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Model(name = "SQL", module = "sql", noTable = true)
public class SqlModel extends BaseModel {}
