package com.cory.model;

import com.cory.db.annotations.Field;
import com.cory.db.annotations.Model;
import com.cory.db.enums.CoryDbType;
import com.cory.model.BaseModel;
import lombok.Data;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Data
@Model(name = "用户角色关系", module = "base")
public class UserRoleRel extends BaseModel {

    @Field(label = "用户ID", type = CoryDbType.BIGINT)
    private Integer userId;

    @Field(label = "角色ID", type = CoryDbType.BIGINT)
    private Integer roleId;
}
