package com.cory.web.controller.base;

import com.cory.model.base.Resource;
import com.cory.sevice.base.ResourceService;
import com.cory.web.controller.BaseAjaxController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Controller
@RequestMapping("/ajax/base/resource/")
public class ResourceController extends BaseAjaxController<Resource> {

    @Autowired
    private ResourceService resourceService;

    public ResourceService getService() {
        return resourceService;
    }
}
