package com.cory.dao.base;

import com.cory.dao.BaseDao;
import com.cory.db.annotations.Dao;
import com.cory.db.annotations.Param;
import com.cory.db.annotations.Select;
import com.cory.model.base.Resource;

import java.util.List;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Dao(model = Resource.class)
public interface ResourceDao extends BaseDao<Resource> {

    @Select(whereSql = "role_id = #{roleId}")
    List<Resource> getByRole(@Param("roleId") Integer roleId);

    @Select(whereSql = "value = #{value}")
    Resource getByValue(@Param("value") String value);
}
