package com.cory.dao.base;

import com.cory.dao.BaseDao;
import com.cory.db.annotations.Dao;
import com.cory.db.annotations.Param;
import com.cory.db.annotations.Select;
import com.cory.model.base.Resource;

import java.util.List;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Dao(model = Resource.class)
public interface ResourceDao extends BaseDao<Resource> {

    @Select(customSql = "SELECT r.* FROM BASE_RESOURCE r WHERE r.IS_DELETED = 0 AND EXISTS(SELECT 1 FROM BASE_ROLE_RESOURCE_REL rel WHERE rel.IS_DELETED = 0 AND r.ID = rel.RESOURCE_ID AND rel.ROLE_ID = #{roleId})")
    List<Resource> getByRole(@Param("roleId") Integer roleId);

    @Select(whereSql = "value = #{value}")
    Resource getByValue(@Param("value") String value);
}
