package com.cory.dao.base;

import com.cory.dao.BaseDao;
import com.cory.db.annotations.Dao;
import com.cory.db.annotations.Param;
import com.cory.db.annotations.Select;
import com.cory.model.base.Role;

import java.util.List;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Dao(model = Role.class)
public interface RoleDao extends BaseDao<Role> {

    @Select(whereSql = "name = #{name}")
    Role getByName(@Param("name") String name);

    @Select(whereSql = "user_id = #{userId}")
    List<Role> getByUser(@Param("userId") Integer userId);
}
