package com.cory.dao;

import com.cory.db.annotations.Dao;
import com.cory.db.annotations.Param;
import com.cory.db.annotations.Select;
import com.cory.model.AccessCount;

import java.util.Map;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Dao(model = AccessCount.class)
public interface AccessCountDao extends BaseDao<AccessCount> {

    @Select(customSql = "select uri, sum(access_count) as count from base_access_count where is_deleted = 0 #![ and day = #{da} ] group by uri order by count desc limit 10")
    Map<String, Integer> stat(@Param("day") String day);
}
