package com.cory.dao;

import com.cory.db.annotations.Dao;
import com.cory.model.AccessCount;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Dao(model = AccessCount.class)
public interface AccessCountDao extends BaseDao<AccessCount> {}
