package com.cory.dao;

import com.cory.db.annotations.Dao;
import com.cory.model.ActionLog;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Dao(model = ActionLog.class)
public interface ActionLogDao extends BaseDao<ActionLog> {
}
