package com.cory.dao;

import com.cory.db.annotations.Dao;
import com.cory.model.ClusterJob;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Dao(model = ClusterJob.class)
public interface ClusterJobDao extends BaseDao<ClusterJob> { }
