package com.cory.dao;

import com.cory.db.annotations.Dao;
import com.cory.db.annotations.Param;
import com.cory.db.annotations.Select;
import com.cory.db.annotations.Update;
import com.cory.enums.ClusterStatus;
import com.cory.model.Cluster;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Dao(model = Cluster.class)
public interface ClusterDao extends BaseDao<Cluster> {

    @Select(whereSql = "ip = #{ip}")
    Cluster getByIp(@Param("ip") String ip);

    @Update(columnSql = "status = #{status}", whereSql = "ip = #{ip}")
    void updateStatus(@Param("ip") String ip, @Param("status") ClusterStatus status);
}
