package com.cory.dao;

import com.cory.db.annotations.Dao;
import com.cory.db.annotations.Param;
import com.cory.db.annotations.Update;
import com.cory.enums.ExportJobStatus;
import com.cory.model.ClusterJob;
import com.cory.model.ExportJob;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Dao(model = ExportJob.class)
public interface ExportJobDao extends BaseDao<ExportJob> {

    @Update(columnSql = "status = #{status}, download_url = #{downloadUrl}, error_msg = #{errorMsg}", whereSql = "code = #{code}")
    void updateStatusAndDownloadUrl(@Param("code") String code,
                                    @Param("status") ExportJobStatus status,
                                    @Param("downloadUrl") String downloadUrl,
                                    @Param("errorMsg") String errorMsg);
}
