package com.cory.dao;

import com.cory.db.annotations.Dao;
import com.cory.model.Feedback;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Dao(model = Feedback.class)
public interface FeedbackDao extends BaseDao<Feedback> {
}
