package com.cory.dao;

import com.cory.db.annotations.Dao;
import com.cory.db.annotations.Sql;
import com.cory.db.enums.CustomSqlType;
import com.cory.model.Feedback;

import java.util.List;
import java.util.Map;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Dao(model = Feedback.class)
public interface FeedbackDao extends BaseDao<Feedback> {

    @Sql(type = CustomSqlType.DDL)
    void customDDLSql(String sql);

    @Sql(type = CustomSqlType.EXECUTE)
    int customExecuteSql(String sql);

    @Sql(type = CustomSqlType.QUERY)
    List<Map<String, Object>> customQuerySql(String sql);
}
