package com.cory.web.controller.base;

import com.cory.model.Cluster;
import com.cory.service.ClusterService;
import com.cory.web.controller.BaseAjaxController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@RestController
@RequestMapping("/ajax/base/cluster/")
public class ClusterController extends BaseAjaxController<Cluster> {

    @Autowired
    private ClusterService clusterService;

    public ClusterService getService() {
        return clusterService;
    }
}
