package com.cory.web.controller.base;

import com.cory.model.DataDict;
import com.cory.service.DatadictService;
import com.cory.web.controller.BaseAjaxController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@RestController
@RequestMapping("/ajax/base/datadict/")
public class DatadictController extends BaseAjaxController<DataDict> {

    @Autowired
    private DatadictService datadictService;

    public DatadictService getService() {
        return datadictService;
    }

    @RequestMapping("refreshCache")
    public boolean refreshCache() {
        datadictService.addRefreshJob();
        return true;
    }

    @RequestMapping("updateShowable")
    public boolean updateShowable(Integer id, boolean showable) {
        this.getService().updateShowable(id, showable);
        return true;
    }
}
