package com.cory.web.controller.base;

import com.cory.model.ExportJob;
import com.cory.service.ExportJobService;
import com.cory.web.controller.BaseAjaxController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@RestController
@RequestMapping("/ajax/base/exportjob/")
public class ExportJobController extends BaseAjaxController<ExportJob> {

    @Autowired
    private ExportJobService exportJobService;

    public ExportJobService getService() {
        return exportJobService;
    }
}
