package com.cory.web.controller.base;

import com.cory.model.Resource;
import com.cory.service.ResourceService;
import com.cory.web.controller.BaseAjaxController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@RestController
@RequestMapping("/ajax/base/resource/")
public class ResourceController extends BaseAjaxController<Resource> {

    @Autowired
    private ResourceService resourceService;

    public ResourceService getService() {
        return resourceService;
    }
}
