package com.cory.service;

import com.cory.dao.AccessCountDao;
import com.cory.model.AccessCount;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Service;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Service
@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS)
public class AccessCountService extends BaseService<AccessCount> {

    @Autowired
    private AccessCountDao accessCountDao;

    public AccessCountDao getDao() {
        return accessCountDao;
    }
}
