package com.cory.service;

import com.cory.dao.ActionLogDao;
import com.cory.model.ActionLog;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Service
@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS)
@Transactional
public class ActionLogService extends BaseService<ActionLog> {

    @Autowired
    private ActionLogDao actionLogDao;

    public ActionLogDao getDao() {
        return actionLogDao;
    }
}
