package com.cory.service;

import com.cory.dao.FeedbackDao;
import com.cory.model.Feedback;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * generated by CodeGenerator on 2017/5/10.
 */
@Service
@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS)
@Transactional
public class FeedbackService extends BaseService<Feedback> {

    @Autowired
    private FeedbackDao feedbackDao;

    public FeedbackDao getDao() {
        return feedbackDao;
    }
}
